# This is a configuration file for the bacon tool
#
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/
# You can also check bacon's own bacon.toml file
#  as an example: https://github.com/Canop/bacon/blob/main/bacon.toml

# This is not really able to be used from here so needs to be copied to each exercise
# From inside of the exercise folder I executed the following command
# find . -maxdepth 2 -type d -exec ln -s ../bacon.toml -r -t {} \;

default_job = "clippy"

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = [
  "cargo",
  "clippy",
  "--all-targets",
  "--color",
  "always",
]
need_stdout = false

[jobs.test]
command = [
  "/bin/bash",
  "-c",
  # Hopefully the sleep gives the build command time to start first and lock the target directory
  "echo \"waiting to build\"; sleep 1; cargo test --color always -- --color always",
]
need_stdout = true

[jobs.build]
command = [
  "cargo",
  "build",
  "--all-targets",
  "--color",
  "always",
]
need_stdout = false

[keybindings]
alt-b = "job:build"
